default_platform(:ios)

platform :ios do
  desc "証明書＆プロビジョニングプロファイルの取得"
  lane :fetch_certificates do
    if ENV["CI"]
      create_keychain(
        name: ENV["MATCH_KEYCHAIN_NAME"],
        password: ENV["MATCH_KEYCHAIN_PASSWORD"],
        default_keychain: true,
        unlock: true,
        timeout: 3600,
        add_to_search_list: true
      )
    end

    sync_code_signing(type: "development")
    sync_code_signing(type: "adhoc")
    sync_code_signing(type: "appstore")
  end

  desc "自動テストの実行"
  lane :run_auto_tests do
    run_tests(
      workspace: "Podcasts.xcworkspace",
      scheme: "Podcasts",
      devices: ["iPhone 11 Pro"]
    )
  end
end
