default_platform(:ios)

platform :ios do
  desc "証明書＆プロビジョニングプロファイルの取得"
  lane :fetch_certificates do
    if ENV["CI"]
      create_keychain(
        name: ENV["MATCH_KEYCHAIN_NAME"],
        password: ENV["MATCH_KEYCHAIN_PASSWORD"],
        default_keychain: true,
        unlock: true,
        timeout: 3600,
        add_to_search_list: true
      )
    end

    sync_code_signing(type: "development")
    sync_code_signing(type: "adhoc")
    sync_code_signing(type: "appstore")
  end

  desc "自動テストの実行"
  lane :run_auto_tests do
    run_tests(
      workspace: "Podcasts.xcworkspace",
      scheme: "Podcasts",
      devices: ["iPhone 11 Pro"]
    )
  end

  desc "IPAのリリース"
  lane :publish_ipa do
    increment_build_number(
      build_number: 1
    )

    increment_version_number(
      version_number: "0.1.0",
      xcodeproj: "Podcasts.xcodeproj"
    )

    build_ios_app(
      configuration: "Release",
      export_method: "app-store",
      export_xcargs: "-allowProvisioningUpdates"
    )
  end
end
